name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Install toolchain
        run: |
          # Install Homebrew if not already present
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # Add Homebrew to PATH
          echo "/opt/homebrew/bin:/opt/homebrew/sbin" >> $GITHUB_PATH
          # Install required tools
          brew install llvm@10 || brew install llvm
          brew install checkra1n/cctools/ld64 checkra1n/cctools/cctools
          # Create symbolic links for LLVM tools
          ln -sf /opt/homebrew/opt/llvm@10/bin/clang /opt/homebrew/bin/clang-10 || ln -sf /opt/homebrew/opt/llvm/bin/clang /opt/homebrew/bin/clang-10
          ln -sf /opt/homebrew/opt/llvm@10/bin/llvm-ar /opt/homebrew/bin/llvm-ar-10 || ln -sf /opt/homebrew/opt/llvm/bin/llvm-ar /opt/homebrew/bin/llvm-ar-10
          ln -sf /opt/homebrew/opt/llvm@10/bin/llvm-ranlib /opt/homebrew/bin/llvm-ranlib-10 || ln -sf /opt/homebrew/opt/llvm/bin/llvm-ranlib /opt/homebrew/bin/llvm-ranlib-10
      - name: Voodoo magic
        id: voodoo
        uses: actions/cache@v4
        with:
          key: ${{ github.event_name }}-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            push-${{ github.ref }}-
            push-
          path: |
            **
      - name: Checkout repository
        if: steps.voodoo.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update repository
        if: steps.voodoo.outputs.cache-hit == 'true'
        run: |
          git fetch --all
          git reset --hard origin/$(git branch --show-current)
          git submodule update --recursive --remote
      - name: Compile
        run: |
          # Add Homebrew LLVM tools to PATH
          export PATH="/opt/homebrew/opt/llvm@10/bin:/opt/homebrew/bin:$PATH"
          EMBEDDED_CC='clang-10' EMBEDDED_AR='llvm-ar-10' EMBEDDED_RANLIB='llvm-ranlib-10' make all
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: PongoOS
          path: |
            build/checkra1n-kpf-pongo
            build/Pongo
            build/Pongo.bin
            build/PongoConsolidated.bin
