name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install toolchain
        run: |
          # Add checkra.in repository
          echo 'deb https://assets.checkra.in/debian /' | sudo tee /etc/apt/sources.list.d/checkra1n.list
          curl -fsSL https://assets.checkra.in/debian/archive.key | sudo tee /etc/apt/trusted.gpg.d/checkra1n.asc
          # Add LLVM repository for clang-10 and tools
          echo 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-10 main' | sudo tee /etc/apt/sources.list.d/llvm.list
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          sudo apt-get update
          # Install required tools
          sudo apt-get install -y ld64 cctools-strip clang-10 llvm-10
          # Ensure llvm-ar-10 and llvm-ranlib-10 are available
          sudo ln -sf /usr/bin/llvm-ar-10 /usr/bin/llvm-ar
          sudo ln -sf /usr/bin/llvm-ranlib-10 /usr/bin/llvm-ranlib
      - name: Voodoo magic
        id: voodoo
        uses: actions/cache@v4
        with:
          key: ${{ github.event_name }}-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            push-${{ github.ref }}-
            push-
          path: |
            **
      - name: Checkout repository
        if: steps.voodoo.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update repository
        if: steps.voodoo.outputs.cache-hit == 'true'
        run: |
          git fetch --all
          git reset --hard origin/$(git branch --show-current)
          git submodule update --recursive --remote
      - name: Compile
        run: EMBEDDED_CC='clang-10' EMBEDDED_AR='llvm-ar-10' EMBEDDED_RANLIB='llvm-ranlib-10' make all
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: PongoOS
          path: |
            build/checkra1n-kpf-pongo
            build/Pongo
            build/Pongo.bin
            build/PongoConsolidated.bin
